# Generated by Django 4.0.1 on 2022-01-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='exit_date',
            field=models.DateField(),
        ),
    ]
